Require at least fin v1.22.0 in the init command
This should be refactored once https://github.com/docksal/docksal/issues/327 is resolved

diff --git a/.docksal/commands/init b/.docksal/commands/init
--- a/.docksal/commands/init
+++ b/.docksal/commands/init
@@ -21,7 +21,27 @@ echo-green () { echo -e "${green}$1${NC}"; }
 echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
 echo-yellow () { echo -e "${yellow}$1${NC}"; }
 
+# Convert version string like 1.2.3 to integer for comparison
+# param $1 version string of 3 components max (e.g. 1.10.3)
+# TODO: remove this once minimal version compatibility checking for commands is implemented in fin
+ver_to_int ()
+{
+	local leading_zeros=$(printf "%03d%03d%03d" $(echo "$1" | tr -d '[:alpha:]' | tr -d '-' | tr '.' ' '))
+	# Remove leading zeroes because otherwise bash tried to handle the number as octal which leads to errors if version contains 9
+	echo "$leading_zeros" | sed "s/^0*//"
+}
+
 #-------------------------- Execution --------------------------------
+
+# Minimum Docksal/Fin version requirement
+# TODO: this should be eventually moved to fin and version requirement defined like `#: fin_minimal_version = 1.22.0`
+# in the file header
+fin_minimal_version="1.22.0"
+if [[ $(ver_to_int $(fin -v)) < $(ver_to_int "$fin_minimal_version") ]]; then
+	echo-red "Minimal fin version required is: $fin_minimal_version"
+	echo -e "Please run ${yellow}fin update${NC} and try again"
+	exit 1
+fi
 
 # Stack initialization
 echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
