Minor init script cleanup
Removed old unnecessary condition

diff --git a/.docksal/commands/init b/.docksal/commands/init
--- a/.docksal/commands/init
+++ b/.docksal/commands/init
@@ -4,8 +4,7 @@
 ##
 ## Usage: fin init
 
-# Abort if anything fails
-set -e
+set -e  # Abort if anything fails
 
 #-------------------------- Helper functions --------------------------------
 
@@ -25,11 +24,8 @@ echo-yellow () { echo -e "${yellow}$1${NC}"; }
 
 # Stack initialization
 echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
-if [[ $DOCKER_RUNNING == "true" ]]; then
-	fin reset -f
-else
-	fin up
-fi
+fin project reset --force
+
 echo "Waiting 10s for MySQL to initialize...";
 sleep 10
 
