Revert "Minor init script cleanup"
This reverts commit ab9cb705560393f9983f7e62d3baa2ffdc9c3ded.

diff --git a/.docksal/commands/init b/.docksal/commands/init
--- a/.docksal/commands/init
+++ b/.docksal/commands/init
@@ -4,7 +4,8 @@
 ##
 ## Usage: fin init
 
-set -e  # Abort if anything fails
+# Abort if anything fails
+set -e
 
 #-------------------------- Helper functions --------------------------------
 
@@ -24,8 +25,11 @@ echo-yellow () { echo -e "${yellow}$1${NC}"; }
 
 # Stack initialization
 echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
-fin project reset --force
-
+if [[ $DOCKER_RUNNING == "true" ]]; then
+	fin reset -f
+else
+	fin up
+fi
 echo "Waiting 10s for MySQL to initialize...";
 sleep 10
 
